use crate::hir;
use crate::ast::{Type, PrivacyTag, ShapeDim, Literal, Pattern, BinaryOp, UnsafeKind, UnaryOp};
use std::collections::{HashMap, HashSet};

pub struct Codegen;

#[derive(Debug, Clone)]
enum LayerParam {
    Linear { in_dim: usize, out_dim: usize },
    Conv2d { in_channels: usize, out_channels: usize, kernel: usize, stride: usize, padding: usize },
    Embedding { num_embeddings: usize, embedding_dim: usize },
}

impl Codegen {
    // -------- 主入口 ----------
    pub fn generate(hir: &hir::HirProgram) -> String {
        let mut code = String::new();
        code.push_str("// Generated by Xiyi Compiler\n\n");
        // code.push_str("extern crate tch;\n");
        // code.push_str("use tch::{Tensor, Kind, Device};\n");
        // code.push_str("use tch::nn::{VarStore, OptimizerConfig, Sgd, Init};\n\n");

        code.push_str("// ---- Privacy labels (compile-time only) ----\n");
        code.push_str("pub trait PrivacyLevel {}\n");
        code.push_str("pub struct Public;\n");
        code.push_str("pub struct Private;\n");
        code.push_str("pub struct Dp<const EPS_NUM: i128, const EPS_DEN: u128>;\n");
        code.push_str("impl PrivacyLevel for Public {}\n");
        code.push_str("impl PrivacyLevel for Private {}\n");
        code.push_str("impl<const N: i128, const D: u128> PrivacyLevel for Dp<N, D> {}\n");
        code.push_str("pub struct PrivacyTensor<T, L: PrivacyLevel>(pub T, pub std::marker::PhantomData<L>);\n\n");

        // 关键修复：这里原来硬编码了一整段 TrainingContext/consume 的 Rust
        // 源码字符串（不是从任何 .xiyi 文件生成出来的，是早期占位脚手架）。
        // 它写死假设裸标识符 String 永远指向 std::string::String——但
        // string.xiyi 现在真的定义了 struct String，本地这个会遮蔽标准库
        // 的 String，导致 consume 方法签名里的 String（本地）跟
        // .to_string() 产出的 String（std）对不上号，编译直接失败。
        // 整个对话过程里没有任何 .xiyi 源码引用过 TrainingContext，这段
        // 纯属遗留脚手架，直接删掉。

        // ---- 生成 proto 枚举 ----
        for proto in &hir.protos {
            code.push_str(&Self::gen_proto(proto));
        }

        let models = &hir.models;
        let fns = &hir.fns;
        let structs = &hir.structs;
        let enums = &hir.enums;
        let consts = &hir.consts;

        let model_names: HashSet<String> = models.iter().map(|m| m.name.clone()).collect();
        let all_symbols = Self::collect_all_symbols(hir);

        for m in models {
            code.push_str(&Self::gen_model_def(m, &all_symbols, &model_names));
        }

        // 先收集所有非 main 的函数
        for f in fns {
            if f.name != "main" {
                code.push_str(&Self::gen_fn_def(f));
            }
        }

        // 处理 main：如果有用户定义的 main，生成它；否则自动生成
        if let Some(main_fn) = fns.iter().find(|f| f.name == "main") {
            code.push_str(&Self::gen_fn_def(main_fn));
        } else {
            if !models.is_empty() {
                code.push_str(&Self::gen_main(hir, &model_names, &all_symbols));
            } else {
                code.push_str("fn main() -> ::std::result::Result<(), Box<dyn std::error::Error>> { ::std::result::Result::Ok(()) }\n");
            }
        }

        for s in structs {
            code.push_str(&Self::gen_struct_def(s));
        }
        for e in enums {
            code.push_str(&Self::gen_enum_def(e));
        }
        // ===== 之前这里完全没有：hir_builder.rs 早就把 implement 块收集进了
        // HirProgram.impls，但 generate() 从来没读过这个字段，导致不管是
        // 结构体还是枚举的 implement 方法，一个都没生成到最终的 Rust 代码
        // 里——这才是 is_some/is_none/unwrap "method not found" 的真正原因。
        // interface（trait）暂时不生成对应的 Rust trait，只生成 inherent
        // impl（这也是这次测试文件唯一用到的形式）；如果以后要支持
        // `implement X for Y` 这种真正实现 trait 的写法，还需要另外
        // 生成 `trait X { ... }` 本身，这个先不做。
        for imp in &hir.impls {
            code.push_str(&Self::gen_implement_def(imp));
        }
        for c in consts {
            code.push_str(&Self::gen_const_def(c));
        }

        code
    }

    // -------- 生成 proto ----------
    fn gen_proto(proto: &hir::HirProto) -> String {
        let mut s = format!("#[derive(Debug, Clone, PartialEq)]\npub enum {} {{\n", proto.name);
        for variant in &proto.variants {
            if let Some(ty) = &variant.ty {
                s.push_str(&format!("    {}({}),\n", variant.name, Self::type_to_rust(ty)));
            } else {
                s.push_str(&format!("    {},\n", variant.name));
            }
        }
        s.push_str("}\n\n");
        s
    }

    // -------- 符号收集 ----------
    fn collect_all_symbols(hir: &hir::HirProgram) -> HashSet<String> {
        let mut symbols = HashSet::new();
        for m in &hir.models {
            if let Some(f) = m.functions.iter().find(|f| f.name == "forward") {
                Self::collect_symbols_from_fn(f, &mut symbols);
            }
        }
        symbols
    }

    fn collect_symbols_from_fn(f: &hir::HirFn, symbols: &mut HashSet<String>) {
        for param in &f.params {
            Self::collect_symbols_from_type(&param.ty, symbols);
        }
        if let Some(ret) = &f.return_type {
            Self::collect_symbols_from_type(ret, symbols);
        }
        Self::collect_symbols_from_block(&f.body, symbols);
    }

    fn collect_symbols_from_type(ty: &Type, symbols: &mut HashSet<String>) {
        match ty {
            Type::Tensor { shape, .. } => {
                for dim in shape {
                    if let ShapeDim::Sym(s) = dim {
                        symbols.insert(s.clone());
                    }
                }
            }
            Type::Privacy(inner, _) => Self::collect_symbols_from_type(inner, symbols),
            _ => {}
        }
    }

    fn collect_symbols_from_block(block: &hir::HirBlock, symbols: &mut HashSet<String>) {
        for stmt in &block.stmts {
            match stmt {
                hir::HirStmt::Expr { expr, span: _ } => Self::collect_symbols_from_expr(expr, symbols),
                hir::HirStmt::Let { name: _, ty, init, mutable: _, persist: _, span: _ } => {
                    if let Some(ty) = ty {
                        Self::collect_symbols_from_type(ty, symbols);
                    }
                    Self::collect_symbols_from_expr(init, symbols);
                }
                hir::HirStmt::Return { expr: Some(expr), span: _ } => Self::collect_symbols_from_expr(expr, symbols),
                hir::HirStmt::While { cond, body, span: _ } => {
                    Self::collect_symbols_from_expr(cond, symbols);
                    Self::collect_symbols_from_block(body, symbols);
                }
                hir::HirStmt::For { var: _, iterable, body, span: _ } => {
                    Self::collect_symbols_from_expr(iterable, symbols);
                    Self::collect_symbols_from_block(body, symbols);
                }
                hir::HirStmt::Loop { body, span: _ } => Self::collect_symbols_from_block(body, symbols),
                hir::HirStmt::Assign { target, expr, span: _ } => {
                    Self::collect_symbols_from_expr(target, symbols);
                    Self::collect_symbols_from_expr(expr, symbols);
                }
                hir::HirStmt::UnsafeBlock { body, kind: _, span: _ } => Self::collect_symbols_from_block(body, symbols),
                _ => {}
            }
        }
    }

    fn collect_symbols_from_expr(expr: &hir::HirExpr, symbols: &mut HashSet<String>) {
        match &expr.kind {
            hir::HirExprKind::Sym(s) => { symbols.insert(s.clone()); }
            hir::HirExprKind::BinaryOp { left, right, .. } => {
                Self::collect_symbols_from_expr(left, symbols);
                Self::collect_symbols_from_expr(right, symbols);
            }
            hir::HirExprKind::Call { args, .. } => {
                for arg in args {
                    match arg {
                        hir::HirCallArg::Positional(e) => Self::collect_symbols_from_expr(e, symbols),
                        hir::HirCallArg::Named(_, e) => Self::collect_symbols_from_expr(e, symbols),
                    }
                }
            }
            hir::HirExprKind::Block(b) => Self::collect_symbols_from_block(b, symbols),
            hir::HirExprKind::FieldAccess { struct_expr, .. } => Self::collect_symbols_from_expr(struct_expr, symbols),
            hir::HirExprKind::Match { cond, arms } => {
                Self::collect_symbols_from_expr(cond, symbols);
                for arm in arms {
                    Self::collect_symbols_from_expr(&arm.expr, symbols);
                }
            }
            hir::HirExprKind::Range { start, end } => {
                Self::collect_symbols_from_expr(start, symbols);
                Self::collect_symbols_from_expr(end, symbols);
            }
            hir::HirExprKind::StructInit { fields, .. } => {
                for (_, e) in fields {
                    Self::collect_symbols_from_expr(e, symbols);
                }
            }
            hir::HirExprKind::Closure { body, .. } => Self::collect_symbols_from_expr(body, symbols),
            hir::HirExprKind::If { kind: _, cond, then_expr, else_expr } => {
                Self::collect_symbols_from_expr(cond, symbols);
                Self::collect_symbols_from_expr(then_expr, symbols);
                if let Some(e) = else_expr {
                    Self::collect_symbols_from_expr(e, symbols);
                }
            }
            hir::HirExprKind::ArrayLiteral(elements) => {
                for elem in elements {
                    Self::collect_symbols_from_expr(elem, symbols);
                }
            }
            hir::HirExprKind::UnsafeBlock { body, kind: _, span: _ } => Self::collect_symbols_from_block(body, symbols),
            hir::HirExprKind::EnumVariantAccess { .. } => {}
            hir::HirExprKind::EnumVariantConstruction { args, .. } => {
                for arg in args {
                    match arg {
                        hir::HirCallArg::Positional(e) => Self::collect_symbols_from_expr(e, symbols),
                        hir::HirCallArg::Named(_, e) => Self::collect_symbols_from_expr(e, symbols),
                    }
                }
            }
            // 新增：一元运算符/类型转换内部也可能嵌套符号引用，不递归会漏收
            hir::HirExprKind::Unary { expr, .. } => Self::collect_symbols_from_expr(expr, symbols),
            hir::HirExprKind::Cast { expr, .. } => Self::collect_symbols_from_expr(expr, symbols),
            // 新增：索引表达式，expr 和 index 两边都要递归
            hir::HirExprKind::Index { expr, index } => {
                Self::collect_symbols_from_expr(expr, symbols);
                Self::collect_symbols_from_expr(index, symbols);
            }
            _ => {}
        }
    }

    // -------- gen_main（自动生成 main，当用户未定义时） ----------
    fn gen_main(hir: &hir::HirProgram, model_names: &HashSet<String>, all_symbols: &HashSet<String>) -> String {
        let top_model_name = model_names.iter().last().map(|s| s.as_str()).unwrap_or("Model");
        let top_model = hir.models.iter().find(|m| m.name == top_model_name).unwrap();

        let mut out_dim = "10".to_string();
        if let Some(forward) = top_model.functions.iter().find(|f| f.name == "forward") {
            if let Some(return_ty) = &forward.return_type {
                let stripped = Self::strip_privacy(return_ty);
                if let Type::Tensor { shape, .. } = stripped {
                    if let Some(ShapeDim::Const(dim)) = shape.last() {
                        out_dim = dim.to_string();
                    }
                }
            }
        }

        let privacy_eps = top_model.privacy_eps.clone();

        let mut syms: Vec<String> = all_symbols.iter().cloned().collect();
        syms.sort();

        let mut s = String::from("fn main() -> ::std::result::Result<(), Box<dyn std::error::Error>> {\n");
        s.push_str("    use tch::Tensor;\n");
        s.push_str("    use tch::nn::{VarStore, OptimizerConfig, Sgd, Init};\n\n");

        if !syms.is_empty() {
            for sym in &syms {
                s.push_str(&format!("    const {}: usize = 2; // symbolic dimension\n", sym));
            }
            s.push_str("\n");
        }

        let model_ty = if syms.is_empty() {
            top_model_name.to_string()
        } else {
            format!("{}::<{}>", top_model_name, syms.join(", "))
        };
        s.push_str(&format!("    let mut model = {}::new()?;\n", model_ty));
        s.push_str("    let mut opt = Sgd::default().build(&model.vs, 0.001)?;\n\n");

        if top_model.training_context_required {
            s.push_str("    let mut ctx = TrainingContext::new(1.0);\n");
        }

        let input_shape = top_model.functions.iter()
            .find(|f| f.name == "forward")
            .and_then(|f| {
                f.params.iter()
                    .find(|p| {
                        let stripped = Self::strip_privacy(&p.ty);
                        matches!(stripped, Type::Tensor { .. })
                    })
                    .and_then(|p| {
                        let stripped = Self::strip_privacy(&p.ty);
                        match stripped {
                            Type::Tensor { shape, .. } => Some(shape.clone()),
                            _ => None,
                        }
                    })
            });

        if let Some(shape) = &input_shape {
            let dims: Vec<String> = shape.iter().map(|dim| match dim {
                ShapeDim::Const(c) => format!("{} as i64", c),
                ShapeDim::Sym(s) => format!("{} as i64", s),
                ShapeDim::Dyn => "1 as i64".to_string(),
            }).collect();
            let dims_str = dims.join(", ");
            s.push_str(&format!(
                "    let x = Tensor::randn(&[{}], (tch::Kind::Float, tch::Device::Cpu));\n",
                dims_str
            ));
        } else {
            if !syms.is_empty() {
                let dims: Vec<String> = syms.iter().map(|s| format!("{} as i64", s)).collect();
                s.push_str(&format!(
                    "    let x = Tensor::randn(&[{}], (tch::Kind::Float, tch::Device::Cpu));\n",
                    dims.join(", ")
                ));
            } else {
                s.push_str("    let x = Tensor::randn(&[2 as i64, 32 as i64], (tch::Kind::Float, tch::Device::Cpu));\n");
            }
        }

        let batch_dim = if let Some(shape) = &input_shape {
            if let Some(first_dim) = shape.first() {
                match first_dim {
                    ShapeDim::Const(c) => format!("{} as i64", c),
                    ShapeDim::Sym(s) => format!("{} as i64", s),
                    ShapeDim::Dyn => "1 as i64".to_string(),
                }
            } else {
                "1 as i64".to_string()
            }
        } else {
            if !syms.is_empty() {
                format!("{} as i64", syms[0])
            } else {
                "2 as i64".to_string()
            }
        };
        s.push_str(&format!(
            "    let target = Tensor::randint_low(0, {}, &[{}], (tch::Kind::Int64, tch::Device::Cpu));\n",
            out_dim, batch_dim
        ));

        s.push_str("    println!(\"Input shape: {:?}\", x.size());\n");

        if let Some(eps) = privacy_eps {
            let eps_lit = if let Some((num, den)) = eps.split_once('/') {
                format!("{}.0/{}.0", num, den)
            } else {
                eps
            };
            s.push_str(&format!("    ctx.consume({}).unwrap();\n", eps_lit));
        }

        if top_model.training_context_required {
            s.push_str("    let output = model.forward(x, &mut ctx);\n");
        } else {
            s.push_str("    let output = model.forward(x);\n");
        }

        s.push_str("    println!(\"Output shape: {:?}\", output.size());\n");

        s.push_str(&format!(
            "    let loss = output.view([-1, {}]).cross_entropy_for_logits(&target.view([-1]));\n",
            out_dim
        ));
        s.push_str("    println!(\"Loss: {:?}\", loss.double_value(&[]));\n");
        s.push_str("    loss.backward();\n");
        s.push_str("    opt.step();\n");
        s.push_str("    println!(\"Optimizer step complete.\");\n\n");

        s.push_str("    ::std::result::Result::Ok(())\n");
        s.push_str("}\n");
        s
    }

    // -------- 辅助 ----------
    fn strip_privacy(ty: &Type) -> Type {
        let mut current = ty;
        while let Type::Privacy(inner, _) = current {
            current = inner;
        }
        current.clone()
    }

    // -------- 模型定义 ----------
    fn gen_model_def(m: &hir::HirModel, all_symbols: &HashSet<String>, model_names: &HashSet<String>) -> String {
        let mut code = String::new();
        code.push_str(&format!("// Model: {}\n", m.name));

        let mut sym_names: Vec<String> = all_symbols.iter().cloned().collect();
        sym_names.sort();

        let generic_decl = if sym_names.is_empty() {
            String::new()
        } else {
            let params: Vec<String> = sym_names.iter().map(|s| format!("const {}: usize", s)).collect();
            format!("<{}>", params.join(", "))
        };
        let type_with_params = if sym_names.is_empty() {
            m.name.clone()
        } else {
            format!("{}<{}>", m.name, sym_names.join(", "))
        };

        let mut layer_params = Vec::new();
        if let Some(f) = m.functions.iter().find(|f| f.name == "forward") {
            Self::collect_layer_params(&f.body, &mut layer_params);
        }

        let sym_map: HashMap<String, String> = all_symbols.iter().map(|s| (s.clone(), s.clone())).collect();

        code.push_str(&format!("struct {}{} {{\n", m.name, generic_decl));
        code.push_str("    pub vs: VarStore,\n");

        for field in &m.fields {
            let ty_str = Self::type_to_rust_with_model_params(&field.ty, &sym_names, model_names);
            code.push_str(&format!("    pub {}: {},\n", field.name, ty_str));
        }

        for (i, param) in layer_params.iter().enumerate() {
            let idx = i + 1;
            match param {
                LayerParam::Linear { .. } => {
                    code.push_str(&format!("    pub w{}: Tensor,\n", idx));
                    code.push_str(&format!("    pub b{}: Tensor,\n", idx));
                }
                LayerParam::Conv2d { .. } => {
                    code.push_str(&format!("    pub w{}: Tensor,\n", idx));
                    code.push_str(&format!("    pub b{}: Tensor,\n", idx));
                }
                LayerParam::Embedding { .. } => {
                    code.push_str(&format!("    pub embed_weight{}: Tensor,\n", idx));
                }
            }
        }
        code.push_str("}\n\n");

        let impl_generic = if sym_names.is_empty() {
            String::new()
        } else {
            let params: Vec<String> = sym_names.iter().map(|s| format!("const {}: usize", s)).collect();
            format!("<{}>", params.join(", "))
        };
        code.push_str(&format!("impl{} {} {{\n", impl_generic, type_with_params));
        code.push_str("    pub fn new() -> Result<Self, tch::TchError> {\n");
        code.push_str("        let vs = VarStore::new(Device::Cpu);\n");
        code.push_str("        let _root = &vs.root();\n");

        for (i, param) in layer_params.iter().enumerate() {
            let idx = i + 1;
            match param {
                LayerParam::Linear { in_dim, out_dim } => {
                    code.push_str(&format!(
                        "        let w{} = _root.var(\"w{}\", &[{} as i64, {} as i64], Init::Randn {{ mean: 0.0, stdev: 0.01 }});\n",
                        idx, idx, in_dim, out_dim
                    ));
                    code.push_str(&format!(
                        "        let b{} = _root.var(\"b{}\", &[{} as i64], Init::Const(0.0));\n",
                        idx, idx, out_dim
                    ));
                }
                LayerParam::Conv2d { in_channels, out_channels, kernel, stride: _, padding: _ } => {
                    code.push_str(&format!(
                        "        let w{} = _root.var(\"w{}\", &[{} as i64, {} as i64, {} as i64, {} as i64], Init::Randn {{ mean: 0.0, stdev: 0.01 }});\n",
                        idx, idx, out_channels, in_channels, kernel, kernel
                    ));
                    code.push_str(&format!(
                        "        let b{} = _root.var(\"b{}\", &[{} as i64], Init::Const(0.0));\n",
                        idx, idx, out_channels
                    ));
                }
                LayerParam::Embedding { num_embeddings, embedding_dim } => {
                    code.push_str(&format!(
                        "        let embed_weight{} = _root.var(\"embed_weight{}\", &[{} as i64, {} as i64], Init::Randn {{ mean: 0.0, stdev: 0.01 }});\n",
                        idx, idx, num_embeddings, embedding_dim
                    ));
                }
            }
        }

        code.push_str("        Ok(Self {\n");
        code.push_str("            vs,\n");

        for field in &m.fields {
            let field_name = &field.name;
            let stripped_ty = Self::strip_privacy(&field.ty);
            if let Type::Struct(ref struct_name) = stripped_ty {
                if model_names.contains(struct_name) {
                    if sym_names.is_empty() {
                        code.push_str(&format!("            {}: {}::new()?,\n", field_name, struct_name));
                    } else {
                        code.push_str(&format!("            {}: {}::<{}>::new()?,\n", field_name, struct_name, sym_names.join(", ")));
                    }
                } else {
                    code.push_str(&format!("            {}: todo!(\"field {} not initialized\"),\n", field_name, field_name));
                }
            } else {
                code.push_str(&format!("            {}: todo!(\"field {} not initialized\"),\n", field_name, field_name));
            }
        }

        for (i, param) in layer_params.iter().enumerate() {
            let idx = i + 1;
            match param {
                LayerParam::Linear { .. } => {
                    code.push_str(&format!("            w{},\n", idx));
                    code.push_str(&format!("            b{},\n", idx));
                }
                LayerParam::Conv2d { .. } => {
                    code.push_str(&format!("            w{},\n", idx));
                    code.push_str(&format!("            b{},\n", idx));
                }
                LayerParam::Embedding { .. } => {
                    code.push_str(&format!("            embed_weight{},\n", idx));
                }
            }
        }
        code.push_str("        })\n");
        code.push_str("    }\n\n");

        let method_names: HashSet<String> = m.functions.iter().map(|f| f.name.clone()).collect();
        for fn_def in &m.functions {
            let is_forward = fn_def.name == "forward";
            code.push_str(&Self::gen_method_def(
                fn_def,
                &layer_params,
                &method_names,
                &sym_map,
                is_forward,
                m.training_context_required,
            ));
        }

        code.push_str("}\n\n");
        code
    }

    // -------- 类型转换辅助 ----------
    fn type_to_rust_with_model_params(ty: &Type, sym_names: &[String], model_names: &HashSet<String>) -> String {
        match ty {
            Type::Struct(name) if model_names.contains(name) => {
                if sym_names.is_empty() {
                    name.clone()
                } else {
                    format!("{}<{}>", name, sym_names.join(", "))
                }
            }
            _ => Self::type_to_rust_with_sym(ty, &HashMap::new()),
        }
    }

    // -------- 收集层参数 ----------
    fn collect_layer_params(block: &hir::HirBlock, params: &mut Vec<LayerParam>) {
        for stmt in &block.stmts {
            match stmt {
                hir::HirStmt::Expr { expr, span: _ } => Self::collect_expr_layer(expr, params),
                hir::HirStmt::Let { init, .. } => Self::collect_expr_layer(init, params),
                hir::HirStmt::Return { expr: Some(e), span: _ } => Self::collect_expr_layer(e, params),
                hir::HirStmt::While { cond, body, .. } => {
                    Self::collect_expr_layer(cond, params);
                    Self::collect_block_layer(body, params);
                }
                hir::HirStmt::For { iterable, body, .. } => {
                    Self::collect_expr_layer(iterable, params);
                    Self::collect_block_layer(body, params);
                }
                hir::HirStmt::Loop { body, .. } => Self::collect_block_layer(body, params),
                hir::HirStmt::Assign { target, expr, .. } => {
                    Self::collect_expr_layer(target, params);
                    Self::collect_expr_layer(expr, params);
                }
                hir::HirStmt::UnsafeBlock { body, .. } => Self::collect_block_layer(body, params),
                _ => {}
            }
        }
    }

    fn collect_block_layer(block: &hir::HirBlock, params: &mut Vec<LayerParam>) {
        for stmt in &block.stmts {
            match stmt {
                hir::HirStmt::Expr { expr, span: _ } => Self::collect_expr_layer(expr, params),
                hir::HirStmt::Let { init, .. } => Self::collect_expr_layer(init, params),
                hir::HirStmt::UnsafeBlock { body, .. } => Self::collect_block_layer(body, params),
                _ => {}
            }
        }
    }

    fn collect_expr_layer(expr: &hir::HirExpr, params: &mut Vec<LayerParam>) {
        match &expr.kind {
            hir::HirExprKind::Call { func, args, .. } => {
                if func == "linear" {
                    let mut in_val = 0;
                    let mut out_val = 0;
                    for arg in args {
                        if let hir::HirCallArg::Named(name, e) = arg {
                            if name == "in" {
                                if let Some(v) = Self::eval_const_int_expr(e) {
                                    in_val = v as usize;
                                }
                            } else if name == "out" {
                                if let Some(v) = Self::eval_const_int_expr(e) {
                                    out_val = v as usize;
                                }
                            }
                        }
                    }
                    if in_val > 0 && out_val > 0 {
                        params.push(LayerParam::Linear { in_dim: in_val, out_dim: out_val });
                    }
                } else if func == "conv2d" {
                    let mut in_channels = 0;
                    let mut out_channels = 0;
                    let mut kernel = 0;
                    let mut stride = 1;
                    let mut padding = 0;
                    for arg in args {
                        if let hir::HirCallArg::Named(name, e) = arg {
                            if name == "in" {
                                if let Some(v) = Self::eval_const_int_expr(e) {
                                    in_channels = v as usize;
                                }
                            } else if name == "out" {
                                if let Some(v) = Self::eval_const_int_expr(e) {
                                    out_channels = v as usize;
                                }
                            } else if name == "kernel" {
                                if let Some(v) = Self::eval_const_int_expr(e) {
                                    kernel = v as usize;
                                }
                            } else if name == "stride" {
                                if let Some(v) = Self::eval_const_int_expr(e) {
                                    stride = v as usize;
                                }
                            } else if name == "padding" {
                                if let Some(v) = Self::eval_const_int_expr(e) {
                                    padding = v as usize;
                                }
                            }
                        }
                    }
                    if in_channels > 0 && out_channels > 0 && kernel > 0 {
                        params.push(LayerParam::Conv2d { in_channels, out_channels, kernel, stride, padding });
                    }
                } else if func == "embedding" {
                    let mut num_embeddings: usize = 0;
                    let mut embedding_dim: usize = 0;
                    for arg in args {
                        if let hir::HirCallArg::Named(name, e) = arg {
                            if name == "num_embeddings" {
                                if let Some(v) = Self::eval_const_int_expr(e) {
                                    num_embeddings = v as usize;
                                }
                            } else if name == "embedding_dim" {
                                if let Some(v) = Self::eval_const_int_expr(e) {
                                    embedding_dim = v as usize;
                                }
                            }
                        }
                    }
                    if num_embeddings > 0 && embedding_dim > 0 {
                        params.push(LayerParam::Embedding { num_embeddings, embedding_dim });
                    }
                }
                for arg in args {
                    match arg {
                        hir::HirCallArg::Positional(e) => Self::collect_expr_layer(e, params),
                        hir::HirCallArg::Named(_, e) => Self::collect_expr_layer(e, params),
                    }
                }
            }
            hir::HirExprKind::BinaryOp { left, right, .. } => {
                Self::collect_expr_layer(left, params);
                Self::collect_expr_layer(right, params);
            }
            hir::HirExprKind::Block(b) => Self::collect_block_layer(b, params),
            hir::HirExprKind::FieldAccess { struct_expr, .. } => Self::collect_expr_layer(struct_expr, params),
            hir::HirExprKind::Match { cond, arms } => {
                Self::collect_expr_layer(cond, params);
                for arm in arms {
                    Self::collect_expr_layer(&arm.expr, params);
                }
            }
            hir::HirExprKind::Range { start, end } => {
                Self::collect_expr_layer(start, params);
                Self::collect_expr_layer(end, params);
            }
            hir::HirExprKind::StructInit { fields, .. } => {
                for (_, e) in fields {
                    Self::collect_expr_layer(e, params);
                }
            }
            hir::HirExprKind::Closure { body, .. } => Self::collect_expr_layer(body, params),
            hir::HirExprKind::If { kind: _, cond, then_expr, else_expr } => {
                Self::collect_expr_layer(cond, params);
                Self::collect_expr_layer(then_expr, params);
                if let Some(e) = else_expr {
                    Self::collect_expr_layer(e, params);
                }
            }
            hir::HirExprKind::ArrayLiteral(elements) => {
                for elem in elements {
                    Self::collect_expr_layer(elem, params);
                }
            }
            hir::HirExprKind::UnsafeBlock { body, .. } => Self::collect_block_layer(body, params),
            hir::HirExprKind::EnumVariantConstruction { args, .. } => {
                for arg in args {
                    match arg {
                        hir::HirCallArg::Positional(e) => Self::collect_expr_layer(e, params),
                        hir::HirCallArg::Named(_, e) => Self::collect_expr_layer(e, params),
                    }
                }
            }
            // 新增：同上，递归进 Unary/Cast 内部
            hir::HirExprKind::Unary { expr, .. } => Self::collect_expr_layer(expr, params),
            hir::HirExprKind::Cast { expr, .. } => Self::collect_expr_layer(expr, params),
            // 新增：索引表达式，expr 和 index 两边都要递归
            hir::HirExprKind::Index { expr, index } => {
                Self::collect_expr_layer(expr, params);
                Self::collect_expr_layer(index, params);
            }
            _ => {}
        }
    }

    fn eval_const_int_expr(expr: &hir::HirExpr) -> Option<i64> {
        match &expr.kind {
            hir::HirExprKind::Literal(Literal::Int(v)) => Some(*v),
            hir::HirExprKind::Unary { op: UnaryOp::Neg, expr } => {
                Self::eval_const_int_expr(expr).map(|v| -v)
            }
            hir::HirExprKind::BinaryOp { op, left, right } => {
                let l = Self::eval_const_int_expr(left)?;
                let r = Self::eval_const_int_expr(right)?;
                match op {
                    BinaryOp::Add => Some(l + r),
                    BinaryOp::Sub => Some(l - r),
                    BinaryOp::Mul => Some(l * r),
                    BinaryOp::Div => if r != 0 { Some(l / r) } else { None },
                    _ => None,
                }
            }
            _ => None,
        }
    }

    // -------- 方法定义（支持 TrainingContext，并插入 let _ = ctx） ----------
    fn gen_method_def(
        f: &hir::HirFn,
        layer_params: &[LayerParam],
        method_names: &HashSet<String>,
        sym_map: &HashMap<String, String>,
        is_forward: bool,
        training_context_required: bool,
    ) -> String {
        let mut s = format!("    pub fn {}(", f.name);

        // ---- 构建参数列表 ----
        let mut params = Vec::new();

        // 1. 处理 self 参数
        let has_self = f.params.iter().any(|p| p.name == "self");
        if has_self {
            if let Some(param) = f.params.iter().find(|p| p.name == "self") {
                match &param.ty {
                    Type::Ref { mutable, inner } => {
                        if let Type::SelfType = &**inner {
                            if *mutable {
                                params.push("&mut self".to_string());
                            } else {
                                params.push("&self".to_string());
                            }
                        } else {
                            let inner_str = Self::type_to_rust_with_sym(inner, sym_map);
                            if *mutable {
                                params.push(format!("&mut {}", inner_str));
                            } else {
                                params.push(format!("&{}", inner_str));
                            }
                        }
                    }
                    Type::SelfType => {
                        params.push("self".to_string());
                    }
                    _ => {
                        let ty_str = Self::type_to_rust_with_sym(&param.ty, sym_map);
                        params.push(format!("self: {}", ty_str));
                    }
                }
            } else {
                params.push("self".to_string());
            }
        }

        // 2. 处理普通参数（跳过 self）
        for param in f.params.iter() {
            if param.name == "self" { continue; }
            let ty_str = Self::type_to_rust_with_sym(&param.ty, sym_map);
            params.push(format!("{}: {}", param.name, ty_str));
        }

        // 3. 如果 forward 需要 TrainingContext，添加 ctx 参数
        if is_forward && training_context_required {
            let has_ctx = f.params.iter().any(|p| p.name == "ctx");
            if !has_ctx {
                params.push("ctx: &mut TrainingContext".to_string());
            }
        }

        // 4. 组合成参数列表字符串
        let params_str = params.join(", ");
        s.push_str(&params_str);
        s.push(')');

        // ---- 返回值 ----
        if let Some(ret) = &f.return_type {
            let ret_str = Self::type_to_rust_with_sym(ret, sym_map);
            s.push_str(&format!(" -> {}", ret_str));
        }

        // ---- 函数体 ----
        let mut counter = 0;
        let body_code = Self::gen_block_with_params(
            &f.body,
            layer_params,
            &mut counter,
            method_names,
            sym_map,
            is_forward,
            training_context_required,
        );
        s.push_str(&body_code);
        s.push('\n');
        s
    }

    // -------- 带参数的块/语句生成 ----------
    fn gen_block_with_params(
        block: &hir::HirBlock,
        layer_params: &[LayerParam],
        counter: &mut usize,
        method_names: &HashSet<String>,
        sym_map: &HashMap<String, String>,
        is_forward: bool,
        training_context_required: bool,
    ) -> String {
        let mut s = String::from(" {\n");

        // ===== 如果 forward 且需要 TrainingContext，插入使用 ctx 的语句 =====
        if is_forward && training_context_required {
            s.push_str("        let _ = ctx;\n");
        }

        let len = block.stmts.len();
        for (i, stmt) in block.stmts.iter().enumerate() {
            let is_last = i == len - 1;
            s.push_str(&Self::gen_stmt_with_params(
                stmt,
                layer_params,
                2,
                is_last,
                counter,
                method_names,
                sym_map,
                is_forward,
            ));
        }
        s.push_str("    }");
        s
    }

    fn gen_stmt_with_params(
        stmt: &hir::HirStmt,
        layer_params: &[LayerParam],
        indent: usize,
        is_last: bool,
        counter: &mut usize,
        method_names: &HashSet<String>,
        sym_map: &HashMap<String, String>,
        is_forward: bool,
    ) -> String {
        let i = "    ".repeat(indent);
        match stmt {
            hir::HirStmt::Let { name, ty, init, mutable, persist, span: _ } => {
                let init_code = Self::gen_expr_with_params(init, layer_params, counter, method_names, sym_map, is_forward);
                let mut_kw = if *mutable { "mut " } else { "" };
                let persist_comment = if *persist { " // persist (domain-persistent)" } else { "" };
                if let Some(ty) = ty {
                    let ty_str = Self::type_to_rust_with_sym(ty, sym_map);
                    format!("{}let {}{}: {} = {};{}\n", i, mut_kw, name, ty_str, init_code, persist_comment)
                } else {
                    format!("{}let {}{} = {};{}\n", i, mut_kw, name, init_code, persist_comment)
                }
            }
            hir::HirStmt::Expr { expr, span: _ } => {
                let expr_code = Self::gen_expr_with_params(expr, layer_params, counter, method_names, sym_map, is_forward);
                if is_last {
                    format!("{}{}\n", i, expr_code)
                } else {
                    format!("{}{};\n", i, expr_code)
                }
            }
            hir::HirStmt::Return { expr: Some(expr), span: _ } => {
                let expr_code = Self::gen_expr_with_params(expr, layer_params, counter, method_names, sym_map, is_forward);
                format!("{}return {};\n", i, expr_code)
            }
            hir::HirStmt::Return { expr: None, span: _ } => format!("{}return;\n", i),
            hir::HirStmt::While { cond, body, span: _ } => {
                let cond_code = Self::gen_expr_with_params(cond, layer_params, counter, method_names, sym_map, is_forward);
                let body_code = Self::gen_block_with_params(body, layer_params, counter, method_names, sym_map, is_forward, false);
                format!("{}while {} {}\n", i, cond_code, body_code)
            }
            hir::HirStmt::For { var, iterable, body, span: _ } => {
                let iter_code = Self::gen_expr_with_params(iterable, layer_params, counter, method_names, sym_map, is_forward);
                let body_code = Self::gen_block_with_params(body, layer_params, counter, method_names, sym_map, is_forward, false);
                format!("{}for {} in {} {}\n", i, var, iter_code, body_code)
            }
            hir::HirStmt::Assign { target, expr, span: _ } => {
                let target_code = Self::gen_expr_with_params(target, layer_params, counter, method_names, sym_map, is_forward);
                let expr_code = Self::gen_expr_with_params(expr, layer_params, counter, method_names, sym_map, is_forward);
                format!("{}{} = {};\n", i, target_code, expr_code)
            }
            hir::HirStmt::Loop { body, span: _ } => {
                let body_code = Self::gen_block_with_params(body, layer_params, counter, method_names, sym_map, is_forward, false);
                format!("{}loop {}\n", i, body_code)
            }
            hir::HirStmt::Break { span: _ } => format!("{}break;\n", i),
            hir::HirStmt::UnsafeBlock { kind, body, span: _ } => {
                let body_code = Self::gen_block_with_params(body, layer_params, counter, method_names, sym_map, is_forward, false);
                let comment = match kind {
                    UnsafeKind::Normal => "unsafe",
                    UnsafeKind::Verify => "// verify unsafe: memory safety relaxed, but logical invariants enforced\n    unsafe",
                };
                format!("{}{} {}\n", i, comment, body_code)
            }
        }
    }

    // ==================== 表达式生成核心（带参数） ====================
    fn gen_expr_with_params(
        expr: &hir::HirExpr,
        layer_params: &[LayerParam],
        counter: &mut usize,
        method_names: &HashSet<String>,
        sym_map: &HashMap<String, String>,
        is_forward: bool,
    ) -> String {
        match &expr.kind {
            hir::HirExprKind::Literal(lit) => {
                match lit {
                    Literal::Int(v) => v.to_string(),
                    Literal::Bool(v) => v.to_string(),
                    Literal::Float(v) => {
                        if v.fract() == 0.0 { format!("{}.0", *v as i64) } else { v.to_string() }
                    }
                    Literal::String(s) => format!("\"{}\"", s),
                    Literal::Unit => "()".to_string(),
                    // 新增：bytes"..." 字节字符串字面量，直译成 Rust 的
                    // &[u8] 字节数组切片字面量，跟规范里"溶解为编译期常量
                    // 数组的切片引用"这条要求是同一个意思——Rust 的
                    // `&[0x47, 0x45, 0x54]` 本身就是一个编译期常量表达式，
                    // 不需要真的手动拆成 static 数组再取引用这么麻烦。
                    Literal::ByteString(bytes) => {
                        let items: Vec<String> = bytes.iter().map(|b| b.to_string()).collect();
                        format!("(&[{}][..])", items.join(", "))
                    }
                }
            }
            hir::HirExprKind::Ident(name) => name.clone(),
            hir::HirExprKind::Sym(name) => sym_map.get(name).cloned().unwrap_or_else(|| name.clone()),
            hir::HirExprKind::BinaryOp { op, left, right } => {
                let l = Self::gen_expr_with_params(left, layer_params, counter, method_names, sym_map, is_forward);
                let r = Self::gen_expr_with_params(right, layer_params, counter, method_names, sym_map, is_forward);
                let op_str = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    BinaryOp::Mul => "*",
                    BinaryOp::Div => "/",
                    BinaryOp::Mod => "%",
                    BinaryOp::Eq => "==",
                    BinaryOp::Neq => "!=",
                    BinaryOp::Lt => "<",
                    BinaryOp::Gt => ">",
                    BinaryOp::Le => "<=",
                    BinaryOp::Ge => ">=",
                    BinaryOp::And => "&&",
                    BinaryOp::Or => "||",
                };
                format!("({}) {} ({})", l, op_str, r)
            }
            hir::HirExprKind::Call { qualifier, func, generic_args, args, is_method } => {
                let generic_args_str = if !generic_args.is_empty() {
                    let args_str: Vec<String> = generic_args.iter()
                        .map(|ty| Self::type_to_rust_with_sym(ty, sym_map))
                        .collect();
                    format!("::<{}>", args_str.join(", "))
                } else {
                    String::new()
                };

                // 新增：限定路径静态调用（qualifier: Some(_)）——目前 parser.rs
                // 实际上还是把 `Type::func(...)` 统一走 EnumVariantConstruction
                // 那条路生成（跟下面 EnumVariantConstruction 分支产出的
                // `TypeName::variant(args)` 是同一种 Rust 语法，静态函数调用
                // 和枚举变体构造在 Rust 里长得一样，不需要区分）。这里加上只是
                // 为了不管以后 parser 从哪条路产出 qualifier: Some(_)，codegen
                // 都能正确处理，不用再补一次。
                if let Some(q) = qualifier {
                    let args_str: Vec<String> = args.iter()
                        .map(|a| match a {
                            hir::HirCallArg::Positional(e) => Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward),
                            hir::HirCallArg::Named(_, e) => Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward),
                        })
                        .collect();
                    return format!("{}::{}{}({})", q, func, generic_args_str, args_str.join(", "));
                }

                let first_pos = args.iter().find_map(|arg| match arg {
                    hir::HirCallArg::Positional(e) => Some(e),
                    _ => None,
                });

                // ----- 所有 tensor.* 内置函数统一调度 -----
                if func.starts_with("tensor.") {
                    return Self::gen_tensor_builtin(
                        func,
                        args,
                        layer_params,
                        counter,
                        method_names,
                        sym_map,
                        is_forward,
                    );
                }

                // ----- 普通算子（linear, conv2d, embedding 等）-----
                if func == "linear" {
                    *counter += 1;
                    let idx = *counter;
                    let receiver = first_pos.map(|e| Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward))
                        .unwrap_or_else(|| "compile_error!(\"linear missing receiver\")".to_string());
                    format!("{}.matmul(&self.w{}) + &self.b{}", receiver, idx, idx)
                }
                else if func == "conv2d" {
                    *counter += 1;
                    let idx = *counter;
                    let receiver = first_pos.map(|e| Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward))
                        .unwrap_or_else(|| "compile_error!(\"conv2d missing receiver\")".to_string());
                    let stride = Self::extract_int_arg_from_args(args, "stride").unwrap_or(1);
                    let padding = Self::extract_int_arg_from_args(args, "padding").unwrap_or(0);
                    format!("({}).conv2d(&self.w{}, Some(&self.b{}), {}, {}, 1, 1)", receiver, idx, idx, stride, padding)
                }
                else if func == "embedding" {
                    *counter += 1;
                    let idx = *counter;
                    let receiver = first_pos.map(|e| Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward))
                        .unwrap_or_else(|| "compile_error!(\"embedding missing receiver\")".to_string());
                    format!("tch::Tensor::embedding(&self.embed_weight{}, &({}), -1, false, false)", idx, receiver)
                }
                else if func == "relu" {
                    let receiver = first_pos.map(|e| Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward))
                        .unwrap_or_else(|| "compile_error!(\"relu missing receiver\")".to_string());
                    format!("({}).relu()", receiver)
                }
                else if func == "dropout" {
                    let rate = Self::extract_float_arg_from_args(args, "rate").unwrap_or(0.5);
                    let receiver = first_pos.map(|e| Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward))
                        .unwrap_or_else(|| "compile_error!(\"dropout missing receiver\")".to_string());
                    format!("({}).dropout({}, true)", receiver, rate)
                }
                else if func == "max_pool2d" {
                    let kernel = Self::extract_int_arg_from_args(args, "kernel").unwrap_or(2);
                    let stride = Self::extract_int_arg_from_args(args, "stride").unwrap_or(kernel);
                    let receiver = first_pos.map(|e| Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward))
                        .unwrap_or_else(|| "compile_error!(\"max_pool2d missing receiver\")".to_string());
                    format!("({}).max_pool2d([{}, {}], [{}, {}], [0, 0], [1, 1], false)", receiver, kernel, kernel, stride, stride)
                }
                else if func == "flatten" {
                    let receiver = first_pos.map(|e| Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward))
                        .unwrap_or_else(|| "compile_error!(\"flatten missing receiver\")".to_string());
                    format!("({}).flatten(1, -1)", receiver)
                }
                else if func == "sum" {
                    let receiver = first_pos.map(|e| Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward))
                        .unwrap_or_else(|| "compile_error!(\"sum missing receiver\")".to_string());
                    format!("({}).sum(Kind::Float)", receiver)
                }
                else if func == "layer_norm" {
                    let receiver = first_pos.map(|e| Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward))
                        .unwrap_or_else(|| "compile_error!(\"layer_norm missing receiver\")".to_string());
                    format!("({}).layer_norm(&[{}], None, None, 1e-5, true)", receiver, args.len())
                }
                else if func == "closure_call" {
                    if args.len() >= 2 {
                        let closure_expr = Self::gen_expr_with_params(
                            match &args[0] { hir::HirCallArg::Positional(e) => e, _ => unreachable!() },
                            layer_params, counter, method_names, sym_map, is_forward
                        );
                        let rest_args: Vec<String> = args[1..].iter()
                            .map(|a| match a {
                                hir::HirCallArg::Positional(e) => Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward),
                                hir::HirCallArg::Named(_, e) => Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward),
                            })
                            .collect();
                        format!("({})({})", closure_expr, rest_args.join(", "))
                    } else {
                        format!("compile_error!(\"closure call requires at least one argument\")")
                    }
                }
                else if func == "print" {
                    if args.len() == 1 {
                        let arg = match &args[0] {
                            hir::HirCallArg::Positional(e) => e,
                            hir::HirCallArg::Named(_, e) => e,
                        };
                        let arg_code = Self::gen_expr_with_params(arg, layer_params, counter, method_names, sym_map, is_forward);
                        format!("println!(\"{}\", {})", "{}", arg_code)
                    } else {
                        format!("compile_error!(\"print only supports one argument currently\");")
                    }
                }
                // 关键修复：`!expr` 以前在 parser.rs 里被脱糖成
                // Call{ func: "not", args: [expr] }，靠这个特判生成 `!(...)`。
                // 现在 parser.rs 已经改成产出真正的
                // HirExprKind::Unary{ op: UnaryOp::Not, .. } 了，对应的代码
                // 生成挪到下面新增的 HirExprKind::Unary 分支里去了，这个
                // 特判是死代码，直接删掉。
                else if func == "panic" {
                    if let Some(arg) = args.first() {
                        let arg_expr = match arg {
                            hir::HirCallArg::Positional(e) => e,
                            hir::HirCallArg::Named(_, e) => e,
                        };
                        let arg_code = Self::gen_expr_with_params(arg_expr, layer_params, counter, method_names, sym_map, is_forward);
                        // 跟 print 用同一个套路：不假设 arg_code 本身就是字符串
                        // 字面量，走 "{}" 格式化，这样调用点传变量也能用。
                        return format!("panic!(\"{}\", {})", "{}", arg_code);
                    } else {
                        return "compile_error!(\"panic requires an argument\")".to_string();
                    }
                }
                // 跟 panic 同一类问题：from_utf8_unchecked 在 sema.rs 里已经
                // 注册成内建函数了，这里补上对应的代码生成——直译成 Rust
                // 标准库自己的 std::str::from_utf8_unchecked。
                else if func == "from_utf8_unchecked" {
                    if let Some(arg) = args.first() {
                        let arg_expr = match arg {
                            hir::HirCallArg::Positional(e) => e,
                            hir::HirCallArg::Named(_, e) => e,
                        };
                        let arg_code = Self::gen_expr_with_params(arg_expr, layer_params, counter, method_names, sym_map, is_forward);
                        return format!("std::str::from_utf8_unchecked({})", arg_code);
                    } else {
                        return "compile_error!(\"from_utf8_unchecked requires an argument\")".to_string();
                    }
                }
                else if *is_method {
                    if method_names.contains(func) {
                        let receiver = first_pos.map(|e| Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward))
                            .unwrap_or_else(|| "compile_error!(\"method call missing receiver\")".to_string());
                        let rest_args: Vec<String> = args[1..].iter()
                            .map(|a| match a {
                                hir::HirCallArg::Positional(e) => Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward),
                                hir::HirCallArg::Named(_, e) => Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward),
                            })
                            .collect();
                        if rest_args.is_empty() {
                            format!("({}).{}{}()", receiver, func, generic_args_str)
                        } else {
                            format!("({}).{}{}({})", receiver, func, generic_args_str, rest_args.join(", "))
                        }
                    } else if args.is_empty() {
                        format!("compile_error!(\"method call requires receiver\")")
                    } else {
                        let receiver = first_pos.map(|e| Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward))
                            .unwrap_or_else(|| "compile_error!(\"method call missing receiver\")".to_string());
                        let rest_args: Vec<String> = args[1..].iter()
                            .map(|a| match a {
                                hir::HirCallArg::Positional(e) => Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward),
                                hir::HirCallArg::Named(_, e) => Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward),
                            })
                            .collect();
                        if rest_args.is_empty() {
                            format!("({}).{}{}()", receiver, func, generic_args_str)
                        } else {
                            format!("({}).{}{}({})", receiver, func, generic_args_str, rest_args.join(", "))
                        }
                    }
                }
                else {
                    let args_str: Vec<String> = args.iter()
                        .map(|a| match a {
                            hir::HirCallArg::Positional(e) => Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward),
                            hir::HirCallArg::Named(_, e) => Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward),
                        })
                        .collect();
                    format!("{}{}({})", func, generic_args_str, args_str.join(", "))
                }
            }
            hir::HirExprKind::StructInit { struct_name, generic_args, fields } => {
                let generic_args_str = if !generic_args.is_empty() {
                    let args_str: Vec<String> = generic_args.iter()
                        .map(|ty| Self::type_to_rust_with_sym(ty, sym_map))
                        .collect();
                    format!("::<{}>", args_str.join(", "))
                } else {
                    String::new()
                };
                let mut code = format!("{}{} {{", struct_name, generic_args_str);
                for (i, (field_name, field_expr)) in fields.iter().enumerate() {
                    if i > 0 { code.push_str(", "); }
                    let field_val = Self::gen_expr_with_params(field_expr, layer_params, counter, method_names, sym_map, is_forward);
                    code.push_str(&format!("{}: {}", field_name, field_val));
                }
                code.push('}');
                code
            }
            hir::HirExprKind::FieldAccess { struct_expr, field_name } => {
                let struct_str = Self::gen_expr_with_params(struct_expr, layer_params, counter, method_names, sym_map, is_forward);
                format!("({}).{}", struct_str, field_name)
            }
            hir::HirExprKind::Range { start, end } => {
                let start_str = Self::gen_expr_with_params(start, layer_params, counter, method_names, sym_map, is_forward);
                let end_str = Self::gen_expr_with_params(end, layer_params, counter, method_names, sym_map, is_forward);
                format!("{}..{}", start_str, end_str)
            }
            hir::HirExprKind::EnumVariantAccess { enum_name, variant_name } => {
                format!("{}::{}", enum_name, variant_name)
            }
            hir::HirExprKind::EnumVariantConstruction { enum_name, generic_args, variant_name, args } => {
                let generic_args_str = if !generic_args.is_empty() {
                    let args_str: Vec<String> = generic_args.iter()
                        .map(|ty| Self::type_to_rust_with_sym(ty, sym_map))
                        .collect();
                    format!("::<{}>", args_str.join(", "))
                } else {
                    String::new()
                };
                let arg_codes: Vec<String> = args.iter()
                    .map(|arg| match arg {
                        hir::HirCallArg::Positional(e) => Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward),
                        hir::HirCallArg::Named(_, e) => Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward),
                    })
                    .collect();
                format!("{}{}::{}({})", enum_name, generic_args_str, variant_name, arg_codes.join(", "))
            }
            hir::HirExprKind::Match { cond, arms } => {
                let cond_code = Self::gen_expr_with_params(cond, layer_params, counter, method_names, sym_map, is_forward);
                let mut arms_code = String::new();
                for arm in arms {
                    let pattern_code = match &arm.pattern {
                        Pattern::EnumVariant { enum_name, variant_name } => {
                            format!("{}::{}", enum_name, variant_name)
                        }
                        Pattern::EnumVariantWithBinding { enum_name, variant_name, binding } => {
                            format!("{}::{}({})", enum_name, variant_name, binding)
                        }
                        Pattern::Wildcard => "_".to_string(),
                    };
                    let arm_expr = Self::gen_expr_with_params(&arm.expr, layer_params, counter, method_names, sym_map, is_forward);
                    arms_code.push_str(&format!("        {} => {},\n", pattern_code, arm_expr));
                }
                format!("match {} {{\n{}}}\n", cond_code, arms_code)
            }
            hir::HirExprKind::Block(b) => Self::gen_block_with_params(b, layer_params, counter, method_names, sym_map, is_forward, false),
            hir::HirExprKind::Closure { param, body } => {
                format!("|{}| {}", param, Self::gen_expr_with_params(body, layer_params, counter, method_names, sym_map, is_forward))
            }
            // kind 对代码生成没有影响：Normal 和 Lack 生成的 Rust 都是
            // `if cond { then } else { ... }`，唯一区别（有没有 else、
            // then 是不是 Unit）已经在 sema 里检查过了，这里不用再分支。
            hir::HirExprKind::If { kind: _, cond, then_expr, else_expr } => {
                let cond_code = Self::gen_expr_with_params(cond, layer_params, counter, method_names, sym_map, is_forward);
                let then_code = Self::gen_expr_with_params(then_expr, layer_params, counter, method_names, sym_map, is_forward);
                let else_code = if let Some(e) = else_expr {
                    Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward)
                } else {
                    "()".to_string()
                };
                format!("if ({}) {{ {} }} else {{ {} }}", cond_code, then_code, else_code)
            }
            hir::HirExprKind::ArrayLiteral(elements) => {
                let elem_codes: Vec<String> = elements.iter()
                    .map(|e| Self::gen_expr_with_params(e, layer_params, counter, method_names, sym_map, is_forward))
                    .collect();
                format!("[{}]", elem_codes.join(", "))
            }
            hir::HirExprKind::UnsafeBlock { kind, body, span: _ } => {
                let body_code = Self::gen_block_with_params(body, layer_params, counter, method_names, sym_map, is_forward, false);
                let comment = match kind {
                    UnsafeKind::Normal => "unsafe",
                    UnsafeKind::Verify => "// verify unsafe: memory safety relaxed, but logical invariants enforced\n    unsafe",
                };
                format!("{} {}", comment, body_code)
            }
            // ===== 新增：一元运算符，直译成 Rust 对应写法 =====
            hir::HirExprKind::Unary { op, expr } => {
                let inner_code = Self::gen_expr_with_params(expr, layer_params, counter, method_names, sym_map, is_forward);
                match op {
                    UnaryOp::Neg => format!("-({})", inner_code),
                    UnaryOp::Not => format!("!({})", inner_code),
                }
            }
            // ===== 新增：as 类型转换 =====
            hir::HirExprKind::Cast { expr, ty } => {
                let inner_code = Self::gen_expr_with_params(expr, layer_params, counter, method_names, sym_map, is_forward);
                let ty_code = Self::type_to_rust_with_sym(ty, sym_map);
                format!("({} as {})", inner_code, ty_code)
            }
            // ===== 新增：索引表达式，直译成 Rust 的 expr[idx] =====
            hir::HirExprKind::Index { expr, index } => {
                let expr_code = Self::gen_expr_with_params(expr, layer_params, counter, method_names, sym_map, is_forward);
                let index_code = Self::gen_expr_with_params(index, layer_params, counter, method_names, sym_map, is_forward);
                format!("{}[{}]", expr_code, index_code)
            }
            // ===== 新增：lack &[T] 空切片字面量，直译成 Rust 的空数组切片 =====
            // `&([] as [T; 0])[..]` 这个写法是为了让 Rust 明确知道空数组
            // 的元素类型是 T（裸 `&[]` 在大多数上下文里 Rust 自己推不出
            // 元素类型，会报 "type annotations needed"）。
            hir::HirExprKind::LackSlice(ty) => {
                let ty_code = Self::type_to_rust_with_sym(ty, sym_map);
                format!("(&([] as [{}; 0])[..])", ty_code)
            }
        }
    }

    fn get_arg<'a>(args: &'a [hir::HirCallArg], pos: usize, name: &str) -> &'a hir::HirExpr {
        // 1. 优先按位置取
        if let Some(arg) = args.get(pos) {
            match arg {
                hir::HirCallArg::Positional(e) => return e,
                hir::HirCallArg::Named(n, e) => {
                    if n == name {
                        return e;
                    }
                }
            }
        }

        // 2. 按名称查找（回退）
        for arg in args {
            if let hir::HirCallArg::Named(n, e) = arg {
                if n == name {
                    return e;
                }
            }
        }

        // 理论上 sema 已检查过，不会走到这里
        panic!("tensor call missing argument '{}' (tried position {} and name)", name, pos + 1)
    }

    fn gen_tensor_builtin(
        func: &str,
        args: &[hir::HirCallArg],
        layer_params: &[LayerParam],
        counter: &mut usize,
        method_names: &HashSet<String>,
        sym_map: &HashMap<String, String>,
        is_forward: bool,
    ) -> String {
        match func {
            "tensor.cond" => Self::gen_tensor_cond(args, layer_params, counter, method_names, sym_map, is_forward),
            "tensor.while_loop" => Self::gen_tensor_while_loop(args, layer_params, counter, method_names, sym_map, is_forward),
            _ => format!("compile_error!(\"Unsupported tensor builtin: {}\")", func),
        }
    }

    fn gen_tensor_cond(
        args: &[hir::HirCallArg],
        layer_params: &[LayerParam],
        counter: &mut usize,
        method_names: &HashSet<String>,
        sym_map: &HashMap<String, String>,
        is_forward: bool,
    ) -> String {
        let input_expr = Self::get_arg(args, 0, "input");
        let cond_expr = Self::get_arg(args, 1, "condition");
        let then_expr = Self::get_arg(args, 2, "then");
        let else_expr = Self::get_arg(args, 3, "else");

        let input_code = Self::gen_expr_with_params(input_expr, layer_params, counter, method_names, sym_map, is_forward);
        let cond_code = Self::gen_expr_with_params(cond_expr, layer_params, counter, method_names, sym_map, is_forward);
        let then_code = Self::gen_expr_with_params(then_expr, layer_params, counter, method_names, sym_map, is_forward);
        let else_code = Self::gen_expr_with_params(else_expr, layer_params, counter, method_names, sym_map, is_forward);

        format!(
            "{{\n    let __x = {};\n    if ({})(__x) {{ {} }} else {{ {} }}\n}}",
            input_code, cond_code, then_code, else_code
        )
    }

    fn gen_tensor_while_loop(
        args: &[hir::HirCallArg],
        layer_params: &[LayerParam],
        counter: &mut usize,
        method_names: &HashSet<String>,
        sym_map: &HashMap<String, String>,
        is_forward: bool,
    ) -> String {
        let init_expr = Self::get_arg(args, 0, "init");
        let cond_expr = Self::get_arg(args, 1, "cond");
        let body_expr = Self::get_arg(args, 2, "body");

        let init_code = Self::gen_expr_with_params(init_expr, layer_params, counter, method_names, sym_map, is_forward);
        let cond_code = Self::gen_expr_with_params(cond_expr, layer_params, counter, method_names, sym_map, is_forward);
        let body_code = Self::gen_expr_with_params(body_expr, layer_params, counter, method_names, sym_map, is_forward);

        format!(
            "{{\n    let mut __x = {};\n    while ({})(__x) {{\n        __x = ({})(__x);\n    }}\n    __x\n}}",
            init_code, cond_code, body_code
        )
    }

    // -------- 无参数表达式生成（增加 Unit 显式处理） ----------
    fn gen_expr(expr: &hir::HirExpr) -> String {
        // 显式处理 Unit 字面量，其他情况委托给带参数版本
        match &expr.kind {
            hir::HirExprKind::Literal(Literal::Unit) => "()".to_string(),
            _ => {
                let mut dummy_counter = 0;
                Self::gen_expr_with_params(
                    expr,
                    &[],
                    &mut dummy_counter,
                    &HashSet::new(),
                    &HashMap::new(),
                    false,
                )
            }
        }
    }

    // -------- 类型转 Rust 字符串（已包含所有基本类型及 TypeParam） ----------
    fn type_to_rust_with_sym(ty: &Type, sym_map: &HashMap<String, String>) -> String {
        match ty {
            Type::I8 => "i8".to_string(),
            Type::I16 => "i16".to_string(),
            Type::I32 => "i32".to_string(),
            Type::I64 => "i64".to_string(),
            Type::I128 => "i128".to_string(),
            Type::U8 => "u8".to_string(),
            Type::U16 => "u16".to_string(),
            Type::U32 => "u32".to_string(),
            Type::U64 => "u64".to_string(),
            Type::U128 => "u128".to_string(),
            Type::F16 => "f16".to_string(),
            Type::F32 => "f32".to_string(),
            Type::F64 => "f64".to_string(),
            Type::Bool => "bool".to_string(),
            Type::Char => "char".to_string(),
            Type::Str => "&str".to_string(),
            Type::Unit => "()".to_string(),
            Type::TypeParam(name) => name.clone(),
            Type::Struct(name) => name.clone(),
            Type::Enum(name) => name.clone(),
            Type::SelfType => "Self".to_string(),
            Type::Generic(name, args) => {
                let args_str: Vec<String> = args.iter()
                    .map(|a| Self::type_to_rust_with_sym(a, sym_map))
                    .collect();
                format!("{}<{}>", name, args_str.join(", "))
            }
            Type::Tensor { dtype: _, shape: _ } => "tch::Tensor".to_string(),
            Type::Privacy(inner, _) => Self::type_to_rust_with_sym(inner, sym_map),
            Type::SymInt => "usize".to_string(),
            Type::ConstIntArray(vals) => {
                format!("[{}]", vals.iter().map(|v| v.to_string()).collect::<Vec<_>>().join(", "))
            }
            Type::Ref { mutable, inner } => {
                let inner_str = Self::type_to_rust_with_sym(inner, sym_map);
                if *mutable {
                    format!("&mut {}", inner_str)
                } else {
                    format!("&{}", inner_str)
                }
            }
            // 新增：切片类型 [T]，跟 Ref 组合生成 &[T]/&mut [T]
            Type::Slice(inner) => format!("[{}]", Self::type_to_rust_with_sym(inner, sym_map)),
        }
    }

    fn type_to_rust(ty: &Type) -> String {
        Self::type_to_rust_with_sym(ty, &HashMap::new())
    }

    // -------- 泛型参数列表渲染：hir::HirGenericParam -> Rust 里 <...> 内的一段 --------
    // generic_params 之前是 Vec<String>，直接 .join(", ") 就行；现在是
    // Vec<HirGenericParam>（带 bounds 了），改成这个共用辅助函数：没有约束时只输出
    // 名字（跟以前行为一致），有约束时输出 `T: Bound1 + Bound2`——目标是生成的 Rust
    // 代码本身合法且保留约束语义，而不是把约束悄悄丢在 codegen 这一层。
    // gen_implement_def / gen_impl_method / gen_struct_def / gen_enum_def / gen_fn_def
    // 这 5 处都改成调用它，不再各自 .join。
    fn format_generic_params(params: &[hir::HirGenericParam]) -> String {
        params
            .iter()
            .map(|gp| {
                if gp.bounds.is_empty() {
                    gp.name.clone()
                } else {
                    format!("{}: {}", gp.name, gp.bounds.join(" + "))
                }
            })
            .collect::<Vec<String>>()
            .join(", ")
    }

    // -------- 无参数块/语句生成（委托给带参数版本，传 false） ----------
    fn gen_block(b: &hir::HirBlock, _allow_tail_expr: bool) -> String {
        let mut dummy_counter = 0;
        Self::gen_block_with_params(
            b,
            &[],
            &mut dummy_counter,
            &HashSet::new(),
            &HashMap::new(),
            false,
            false,
        )
    }

    fn gen_stmt(stmt: &hir::HirStmt, indent: usize, is_last: bool, _allow_tail_expr: bool) -> String {
        let mut dummy_counter = 0;
        Self::gen_stmt_with_params(
            stmt,
            &[],
            indent,
            is_last,
            &mut dummy_counter,
            &HashSet::new(),
            &HashMap::new(),
            false,
        )
    }

    // -------- implement 块：生成 impl<...> Target { ... } ----------
    // 复用 gen_block（跟 gen_fn_def 生成普通函数体是同一套逻辑），方法体
    // 内部不涉及 model 专属的 layer_params/TrainingContext 那些东西，跟
    // 普通函数没有本质区别，唯一的差异是要处理 self 接收者的三种写法。
    fn gen_implement_def(imp: &hir::HirImplement) -> String {
        let generic = if imp.generic_params.is_empty() {
            String::new()
        } else {
            format!("<{}>", Self::format_generic_params(&imp.generic_params))
        };
        let target = Self::type_to_rust(&imp.target_type);
        let mut code = format!("impl{} {} {{\n", generic, target);
        for f in &imp.functions {
            code.push_str(&Self::gen_impl_method(f));
        }
        code.push_str("}\n\n");
        code
    }

    fn gen_impl_method(f: &hir::HirFn) -> String {
        let generic = if f.generic_params.is_empty() {
            String::new()
        } else {
            format!("<{}>", Self::format_generic_params(&f.generic_params))
        };

        let mut params_str: Vec<String> = Vec::new();
        for p in &f.params {
            if p.name == "self" {
                match &p.ty {
                    Type::Ref { mutable, inner } if matches!(**inner, Type::SelfType) => {
                        params_str.push(if *mutable { "&mut self".to_string() } else { "&self".to_string() });
                    }
                    Type::SelfType => params_str.push("self".to_string()),
                    other => {
                        // 不常见的写法（比如 self: Box<Self>），原样转成类型标注
                        params_str.push(format!("self: {}", Self::type_to_rust(other)));
                    }
                }
            } else {
                params_str.push(format!("{}: {}", p.name, Self::type_to_rust(&p.ty)));
            }
        }

        let mut s = format!("    pub fn {}{}({})", f.name, generic, params_str.join(", "));
        if let Some(ret) = &f.return_type {
            s.push_str(&format!(" -> {}", Self::type_to_rust(ret)));
        }
        s.push_str(&Self::gen_block(&f.body, true));
        s.push('\n');
        s
    }

    // -------- 结构体、枚举、常量 ----------
    // 更新：支持泛型
    fn gen_struct_def(s: &hir::HirStruct) -> String {
        let generic = if s.generic_params.is_empty() {
            String::new()
        } else {
            format!("<{}>", Self::format_generic_params(&s.generic_params))
        };
        let mut code = format!("#[derive(Debug, Clone, PartialEq)]\nstruct {}{} {{\n", s.name, generic);
        for field in &s.fields {
            let ty = Self::type_to_rust(&field.ty);
            code.push_str(&format!("    pub {}: {},\n", field.name, ty));
        }
        code.push_str("}\n\n");
        code
    }

    // 更新：支持泛型，变体带类型
    fn gen_enum_def(e: &hir::HirEnum) -> String {
        let generic = if e.generic_params.is_empty() {
            String::new()
        } else {
            format!("<{}>", Self::format_generic_params(&e.generic_params))
        };
        let mut code = format!("#[derive(Debug, Clone, PartialEq)]\nenum {}{} {{\n", e.name, generic);
        for variant in &e.variants {
            if let Some(ty) = &variant.ty {
                let ty_str = Self::type_to_rust(ty);
                code.push_str(&format!("    {}({}),\n", variant.name, ty_str));
            } else {
                code.push_str(&format!("    {},\n", variant.name));
            }
        }
        code.push_str("}\n\n");
        code
    }

    fn gen_const_def(c: &hir::HirConst) -> String {
        let value = Self::gen_expr(&c.value);
        format!("const {}: {} = {};\n\n", c.name, Self::type_to_rust(&c.ty), value)
    }

    // -------- 普通函数定义（对 main 特殊处理） ----------
    fn gen_fn_def(f: &hir::HirFn) -> String {
        // 特殊处理 main 函数
        if f.name == "main" {
            return Self::gen_main_function(f);
        }

        // 补上泛型参数，跟 gen_struct_def / gen_enum_def 保持一致，
        // 否则 fn id(x: T) -> T 里的 T 在 Rust 里找不到定义（E0425）
        let generic = if f.generic_params.is_empty() {
            String::new()
        } else {
            format!("<{}>", Self::format_generic_params(&f.generic_params))
        };

        let mut s = format!("fn {}{}(", f.name, generic);
        for (i, p) in f.params.iter().enumerate() {
            if i > 0 { s.push_str(", "); }
            s.push_str(&format!("{}: {}", p.name, Self::type_to_rust(&p.ty)));
        }
        s.push(')');
        if let Some(ret) = &f.return_type {
            s.push_str(&format!(" -> {}", Self::type_to_rust(ret)));
        }
        s.push_str(&Self::gen_block(&f.body, true));
        s
    }

    // -------- 生成用户定义的 main 函数（转换为 exit） ----------
    fn gen_main_function(f: &hir::HirFn) -> String {
        let mut s = String::from("fn main() -> ! {\n");
        
        // 生成函数体语句
        let stmts = &f.body.stmts;
        let len = stmts.len();
        
        for (i, stmt) in stmts.iter().enumerate() {
            let is_last = i == len - 1;
            match stmt {
                hir::HirStmt::Return { expr: Some(expr), span: _ } => {
                    let expr_code = Self::gen_expr(expr);
                    s.push_str(&format!("    std::process::exit({});\n", expr_code));
                }
                hir::HirStmt::Return { expr: None, span: _ } => {
                    s.push_str("    std::process::exit(0);\n");
                }
                hir::HirStmt::Expr { expr, span: _ } if is_last => {
                    let expr_code = Self::gen_expr(expr);
                    s.push_str(&format!("    std::process::exit({});\n", expr_code));
                }
                hir::HirStmt::Expr { expr, span: _ } => {
                    let expr_code = Self::gen_expr(expr);
                    s.push_str(&format!("    {};\n", expr_code));
                }
                _ => {
                    // 其他语句（如 let, while, loop 等）使用通用的语句生成
                    s.push_str(&Self::gen_stmt(stmt, 1, false, false));
                }
            }
        }
        
        // 如果函数体为空或没有显式退出，默认返回 0
        if !s.contains("std::process::exit") {
            s.push_str("    std::process::exit(0);\n");
        }
        s.push_str("}\n");
        s
    }

    // -------- 参数提取辅助 ----------
    fn extract_int_arg_from_args(args: &[hir::HirCallArg], name: &str) -> Option<i64> {
        for arg in args {
            if let hir::HirCallArg::Named(n, expr) = arg {
                if n == name {
                    if let hir::HirExprKind::Literal(Literal::Int(v)) = &expr.kind {
                        return Some(*v);
                    }
                }
            }
        }
        None
    }

    fn extract_float_arg_from_args(args: &[hir::HirCallArg], name: &str) -> Option<f64> {
        for arg in args {
            if let hir::HirCallArg::Named(n, expr) = arg {
                if n == name {
                    match &expr.kind {
                        hir::HirExprKind::Literal(Literal::Float(v)) => return Some(*v),
                        hir::HirExprKind::Literal(Literal::Int(v)) => return Some(*v as f64),
                        _ => {}
                    }
                }
            }
        }
        None
    }
}